### ISSUE TITLE
失物招领

### ISSUE THREAD

**Issue by minneyy** [septzhang/LostAndFoundRevision#2]
想求一下数据库文档，谢谢你求求了 麻烦看到理理我吧

**Comment by septzhang** [comment]
好的
项目里没有么

**Comment by minneyy** [comment]
没有，我自己试着建了一下，也没有建好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月11日(星期三) 中午12:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [septzhang/LostAndFoundRevision] 失物招领 (Issue #2)





 
好的
 项目里没有么

**Comment by septzhang** [comment]
我马上上传

**Comment by minneyy** [comment]
谢谢你，如果方便的话，可以加个QQ嘛&nbsp; 2695982724 在QQ上传给我也可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月11日(星期三) 中午1:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [septzhang/LostAndFoundRevision] 失物招领 (Issue #2)





 
我马上上传

**Comment by septzhang** [comment]
OK

**Comment by septzhang** [comment]
SQL文件已上传
